export const questionWords = {
  allergy: 'аллергию',
  heart: 'сердце',
  joint: 'суставы',
  asthma: 'астму',
  healthSkin: 'УФ индекс',
  head: 'головные боли',
  ice: 'гололёд',
  wind: 'сильный ветер',
  snow: 'снежный покров',
  washCar: 'мойку машины',
  precipitation: 'осадки на выходные',
  waterTemp: 'воду в водоемах',
  touristsSkin: 'УФ индекс',
  touristsFrosts: 'заморозки',
  rain: 'осадки - дождь',
  hailstones: 'град',
  countrymenFrosts: 'заморозки',
  ventilation: 'вентиляцию теплиц',
}
